config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: [ :new, :create, :index ]
  end
  resources :reviews, only: [ :show ]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORY = ["chinese", "italian", "japanese", "french", "belgian"]
  has_many :reviews, :dependent => :destroy
  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: CATEGORY, allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  RATING = [0, 1, 2, 3, 4, 5]
  belongs_to :restaurant
  validates :content, presence: true
  validates :rating, presence: true, inclusion: { in: RATING, allow_nil: false }
  validates_numericality_of :rating
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to restaurant_path(@restaurant)
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy

    redirect_to restaurants_path
  end

  private

    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :description, :stars, :phone_number, :category)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = Restaurant.find(params[:restaurant_id])
    if @review.save
      redirect_to restaurant_path(params[:restaurant_id])
    else
      render 'new'
    end
  end

  def index
    @reviews = Review.all
  end


  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/review_helper.rb
module ReviewHelper
end

app/views/layouts/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Notification -->
    <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
      <div class="badge-container">
        <i class="fa fa-envelope-o"></i>
        <div class="badge badge-blue">3</div>
      </div>
    <% end %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
            <% end %>
          </li>
          <li>
            <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
            <% end %>
          </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Add a restaurant"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <nav class="navbar-wagon"> </nav>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <%= f.error_notification %>
<div class="container">
  <div class="col-sm-6 col-sm-offset-3">
    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :address %>
      <%= f.input :phone_number %>
      <%= f.input :category, collection: Restaurant::CATEGORY %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
  </div>
</div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="text-center">
  <h1>Editing Restaurant</h1>
</div>

  <%= render 'form', restaurant: @restaurant %>
<div class="text-center">
  <%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<div class="text-center"><h1>Restaurants</h1></div>
<div class="container">
    <% @restaurants.each do |restaurant| %>
      <div class="card ">
        <div class="row">
          <div class="col-sm-4">
            <h2><%= restaurant.name %></h2>
            <p>Address : <%= restaurant.address %></p>
            <p>Category : <%= restaurant.category %></p>
            <p>Phone Number : <%= restaurant.phone_number %></p>

            <%= link_to 'Show', restaurant %>

            <%= link_to 'Edit', edit_restaurant_path(restaurant) %>

           <%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %>
          </div>
        </div>
      </div>
    <% end %>
</div>

<br>
<div class="text-center">
  <%= link_to 'New Restaurant', new_restaurant_path %>
</div>

app/views/restaurants/new.html.erb
<div class="text-center">
  <h1>New Restaurant</h1>
</div>

  <%= render 'form', restaurant: @restaurant %>
<div class="text-center">
  <%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="col-sm-6 col-sm-offset-3">
    <h1><strong><%= @restaurant.name %></strong></h1>

    <p>
      <strong>Address :</strong>
      <%= @restaurant.address %>
    </p>

    <p>
      <strong>Category :</strong>
      <%= @restaurant.category %>
    </p>
    <p>
      <strong>Phone Number :</strong>
      <%= @restaurant.phone_number %>
    </p>
  </div>
</div>

<div class="text-center">
  <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn-primary" %>|
  <%= link_to 'Back to All Restaurants', restaurants_path, class: "btn-primary"  %>
  |
  <%= link_to 'See Reviews', restaurant_reviews_path(@restaurant), class: "btn-primary"  %>
  |
  <%= link_to 'Add a Review', new_restaurant_review_path(@restaurant), class: "btn-primary"  %>
</div>

app/views/reviews/index.html.erb
<div class="text-center"><h1>Reviews</h1></div>
<div class="container padded">
  <div class="col-sm-12">
    <% @reviews.each do |review| %>
      <p><%= review.content %></p>
      <p><%= review.rating %></p>
    <% end %>
  </div>
</div>

<br>
<div class="text-center">
<%= link_to 'back to restaurant', restaurant_path(params[:restaurant_id]) %>
</div>

app/views/reviews/new.html.erb
<div class="text-center">
  <h1>New Review</h1>
</div>
<div class="container padded">
  <div class="row">
    <div class="col-sm-12">
      <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating, collection: Review::RATING%>
      <%= f.submit "add a review", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-sm-6">
      <%= link_to "Back to reviews", restaurant_reviews_path, class: "btn btn-primary"%>
    </div>
    <div class="col-sm-6">
        <%= link_to 'Back to restaurant', restaurant_path(params[:restaurant_id]), class: "btn btn-primary" %>
    </div>
  </div>
</div>